//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LectorCvsResultados
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANALISTINDEXUNG
    {
        public decimal ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<decimal> LINEINDEX { get; set; }
        public Nullable<decimal> RESULT { get; set; }
        public Nullable<decimal> FECHANUM { get; set; }
        public Nullable<decimal> MESNUM { get; set; }
        public Nullable<decimal> DIAMESNUM { get; set; }
        public Nullable<decimal> DIASEMNUM { get; set; }
        public Nullable<decimal> ULTIMOTIMESPAN { get; set; }
        public Nullable<decimal> CANTIDADULTTIMESPAN { get; set; }
    }
}
