
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LectorCvsResultados
{

using System;
    using System.Collections.Generic;
    
public partial class ANDATAGENINFO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ANDATAGENINFO()
    {

        this.FLASHORDERED = new HashSet<FLASHORDERED>();

        this.FLASHORDERED1 = new HashSet<FLASHORDERED>();

        this.FLASHORDERED2 = new HashSet<FLASHORDERED>();

        this.FLASHORDERED3 = new HashSet<FLASHORDERED>();

    }


    public decimal ID { get; set; }

    public decimal GHOME { get; set; }

    public decimal GAWAY { get; set; }

    public decimal TOTALG { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FLASHORDERED> FLASHORDERED { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FLASHORDERED> FLASHORDERED1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FLASHORDERED> FLASHORDERED2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FLASHORDERED> FLASHORDERED3 { get; set; }

}

}
