
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LectorCvsResultados
{

using System;
    using System.Collections.Generic;
    
public partial class ANDATAPERCENTUNG
{

    public decimal ID { get; set; }

    public System.DateTime FECHA { get; set; }

    public decimal FECHANUM { get; set; }

    public decimal PERCENT { get; set; }

    public decimal DIFERENCIAG { get; set; }

    public decimal MESNUM { get; set; }

    public decimal DIAMES { get; set; }

    public decimal DIASEM { get; set; }

    public decimal DIAANIO { get; set; }

    public decimal TIPOORDEN { get; set; }

}

}
