
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LectorCvsResultados
{

using System;
    using System.Collections.Generic;
    
public partial class ANDATASELECTEDINFO
{

    public decimal ID { get; set; }

    public decimal FECHANUM { get; set; }

    public decimal SPANGLGEN { get; set; }

    public decimal RANKSPANGLGEN { get; set; }

    public decimal SPANGLDIASEM { get; set; }

    public decimal RANKSPANGLDIASEM { get; set; }

    public decimal SPANGLDIAMES { get; set; }

    public decimal RANKSPANGLDIAMES { get; set; }

    public decimal SPANTABGEN { get; set; }

    public decimal RANKSPANTABGEN { get; set; }

    public decimal SPANTABDIASEM { get; set; }

    public decimal RANKSPANTABDIASEM { get; set; }

    public decimal SPANTABDIAMES { get; set; }

    public decimal RANKSPANTABDIAMES { get; set; }

    public decimal DIFERENCIAG { get; set; }

    public decimal DIASEM { get; set; }

    public decimal DIAMES { get; set; }

}

}
