
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LectorCvsResultados
{

using System;
    using System.Collections.Generic;
    
public partial class ANDATAMINRANK
{

    public decimal ID { get; set; }

    public int FECHANUM { get; set; }

    public int INFOAGRUPDIASEMMESTI { get; set; }

    public int INFOAGRUPDIASEMMESGL { get; set; }

    public int RANKSPANACTUALGEN { get; set; }

    public int RANKSPANACTUALDIASEM { get; set; }

    public int RANKSPANACTUALDIAMES { get; set; }

    public int RANKSPANACTUALGLGEN { get; set; }

    public int RANKSPANACTUALGLDIASEM { get; set; }

    public int RANKSPANACTUALGLDIAMES { get; set; }

    public int RANKSPANACTUALGLDIAANIO { get; set; }

    public int RANKSPANACTUALDIAANIO { get; set; }

    public int DIASEM { get; set; }

    public int DIAMES { get; set; }

    public int DIAANIO { get; set; }

    public Nullable<int> DIFERENCIAG { get; set; }

    public string KEYRANK { get; set; }

    public string KEYRANKGRAL { get; set; }

}

}
