//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LectorCvsResultados
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class FLASHORDERED
    {
        public decimal ID { get; set; }
        public Nullable<decimal> TABINDEX { get; set; }
        public string RESULT { get; set; }
        public Nullable<decimal> GHOME { get; set; }
        public Nullable<decimal> GAWAY { get; set; }
        public Nullable<decimal> DIFERENCIAG { get; set; }
        public Nullable<decimal> TOTALG { get; set; }
        public string GROUPLETTER { get; set; }
        public Nullable<decimal> TABINDEXLETTER { get; set; }
        public Nullable<decimal> DIASEM { get; set; }
        public Nullable<decimal> DIAMES { get; set; }
        public Nullable<decimal> DIAANIO { get; set; }
        public Nullable<decimal> SPANDIARIOACTUAL { get; set; }
        public Nullable<decimal> SPANDIARIOHISTORICO { get; set; }
        public Nullable<decimal> SPANSEMANAACTUAL { get; set; }
        public Nullable<decimal> SPANSEMANAHISTORICO { get; set; }
        public Nullable<decimal> SPANMESACTUAL { get; set; }
        public Nullable<decimal> SPANMESHISTORICO { get; set; }
        public Nullable<decimal> SPANANIOACTUAL { get; set; }
        public Nullable<decimal> SPANANIOHISTORICO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        [NotMapped]
        public string Hora { get; set; }
        [NotMapped]
        public string Estado { get; set; }
        [NotMapped]
        public string Home { get; set; }
        [NotMapped]
        public string Away { get; set; }
        [NotMapped]
        public string Half { get; set; }
        [NotMapped]
        public int intChar { get; set; }

    }
}
