
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LectorCvsResultados
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class FLASHORDERED
    {

        public decimal ID { get; set; }

        public int TABINDEX { get; set; }

        public string RESULT { get; set; }

        public int GHOME { get; set; }

        public int GAWAY { get; set; }

        public int DIFERENCIAG { get; set; }

        public int TOTALG { get; set; }

        public string GROUPLETTER { get; set; }

        public int TABINDEXLETTER { get; set; }

        public int DIASEM { get; set; }

        public int DIAMES { get; set; }

        public int DIAANIO { get; set; }

        public Nullable<int> SPANTIDIAACT { get; set; }

        public int SPANTIDIAHIST { get; set; }

        public Nullable<int> SPANTISEMACT { get; set; }

        public int SPANTISEMHIST { get; set; }

        public Nullable<int> SPANTIMESACT { get; set; }

        public int SPANTIMESHIST { get; set; }

        public Nullable<int> SPANTIANIACT { get; set; }

        public int SPANTIANIHIST { get; set; }

        public Nullable<int> SPANTIGLDIAACT { get; set; }

        public int SPANTIGLDIAHIST { get; set; }

        public Nullable<int> SPANTIGLSEMACT { get; set; }

        public int SPANTIGLSEMHIST { get; set; }

        public Nullable<int> SPANTIGLMESACT { get; set; }

        public int SPANTIGLMESHIST { get; set; }

        public Nullable<int> SPANTIGLANIACT { get; set; }

        public int SPANTIGLANIHIST { get; set; }

        public System.DateTime FECHA { get; set; }

        public int FECHANUM { get; set; }

        public int TABINDEXSEQ { get; set; }

        public int TABINDEXLETTERSEQ { get; set; }

        public int MESNUM { get; set; }

        public int IDCOMPETITION { get; set; }

        public int TABINDEXCOMPETITION { get; set; }

        public decimal TABINDEXCOMPETSEQ { get; set; }

        [NotMapped]
        public string Hora { get; set; }
        [NotMapped]
        public string Estado { get; set; }
        [NotMapped]
        public string Home { get; set; }
        [NotMapped]
        public string Away { get; set; }
        [NotMapped]
        public string Half { get; set; }
        [NotMapped]
        public int intChar { get; set; }

        public override string ToString()
        {
            return TABINDEX + ";" + RESULT + ";" + GHOME + ";" + GAWAY + ";" + DIFERENCIAG + ";" + TOTALG + ";" + GROUPLETTER + ";" + TABINDEXLETTER + ";" + DIASEM + ";" + DIAMES + ";" + DIAANIO + ";" + SPANTIDIAACT + ";" + SPANTIDIAHIST + ";" + SPANTISEMACT + ";" + SPANTISEMHIST + ";" + SPANTIMESACT + ";" + SPANTIMESHIST + ";" + SPANTIANIACT + ";" + SPANTIANIHIST + ";" + SPANTIGLDIAACT + ";" + SPANTIGLDIAHIST + ";" + SPANTIGLSEMACT + ";" + SPANTIGLSEMHIST + ";" + SPANTIGLMESACT + ";" + SPANTIGLMESHIST + ";" + SPANTIGLANIACT + ";" + SPANTIGLANIHIST + ";" + FECHA + ";" + FECHANUM + ";" + TABINDEXSEQ + ";" + TABINDEXLETTERSEQ + ";" + Hora + ";" + Estado + ";" + Home + ";" + Away + ";" + Half + ";" + intChar;
        }

    }

}
