
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LectorCvsResultados
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class FLASHORDERED
{

    public decimal ID { get; set; }

    public Nullable<int> TABINDEX { get; set; }

    public string RESULT { get; set; }

    public Nullable<int> GHOME { get; set; }

    public Nullable<int> GAWAY { get; set; }

    public Nullable<int> DIFERENCIAG { get; set; }

    public Nullable<int> TOTALG { get; set; }

    public string GROUPLETTER { get; set; }

    public Nullable<int> TABINDEXLETTER { get; set; }

    public Nullable<int> DIASEM { get; set; }

    public Nullable<int> DIAMES { get; set; }

    public Nullable<int> DIAANIO { get; set; }

    public Nullable<int> SPANDIARIOACTUAL { get; set; }

    public Nullable<int> SPANDIARIOHISTORICO { get; set; }

    public Nullable<int> SPANSEMANAACTUAL { get; set; }

    public Nullable<int> SPANSEMANAHISTORICO { get; set; }

    public Nullable<int> SPANMESACTUAL { get; set; }

    public Nullable<int> SPANMESHISTORICO { get; set; }

    public Nullable<int> SPANANIOACTUAL { get; set; }

    public Nullable<int> SPANANIOHISTORICO { get; set; }

    public Nullable<System.DateTime> FECHA { get; set; }

    public Nullable<int> FECHANUM { get; set; }

    public Nullable<int> TABINDEXSEQ { get; set; }

    public Nullable<decimal> TABINDEXLETTERSEQ { get; set; }

        [NotMapped]
        public string Hora { get; set; }
        [NotMapped]
        public string Estado { get; set; }
        [NotMapped]
        public string Home { get; set; }
        [NotMapped]
        public string Away { get; set; }
        [NotMapped]
        public string Half { get; set; }
        [NotMapped]
        public int intChar { get; set; }

        public override string ToString()
        {
            return TABINDEX + ";" + RESULT + ";" + GHOME + ";" + GAWAY + ";" + DIFERENCIAG + ";" + TOTALG + ";" + GROUPLETTER + ";" + TABINDEXLETTER + ";" + DIASEM + ";" + DIAMES + ";" + DIAANIO + ";" + SPANDIARIOACTUAL + ";" + SPANDIARIOHISTORICO + ";" + SPANSEMANAACTUAL + ";" + SPANSEMANAHISTORICO + ";" + SPANMESACTUAL + ";" + SPANMESHISTORICO + ";" + SPANANIOACTUAL + ";" + SPANANIOHISTORICO + ";" + FECHA + ";" + FECHANUM + ";" + TABINDEXSEQ + ";" + TABINDEXLETTERSEQ + ";" + Hora + ";" + Estado + ";" + Home + ";" + Away + ";" + Half + ";" + intChar;
        }
    }

}
