
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LectorCvsResultados
{

using System;
    using System.Collections.Generic;
    
public partial class TOTALESDIAGROPTAB
{

    public decimal FECHANUM { get; set; }

    public string GROUPLETTER { get; set; }

    public decimal TOTAL { get; set; }

}

}
