//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LectorCvsResultados
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERRESULTTABLESFS
    {
        public decimal ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<decimal> TABINDEX { get; set; }
        public string HORA { get; set; }
        public string MARCADOR { get; set; }
        public Nullable<decimal> GLOCAL { get; set; }
        public Nullable<decimal> GVISITANTE { get; set; }
        public Nullable<decimal> DIFERENCIAG { get; set; }
        public Nullable<decimal> TOTALG { get; set; }
        public Nullable<decimal> FECHANUM { get; set; }
        public Nullable<decimal> MESNUM { get; set; }
        public Nullable<decimal> DIAMESNUM { get; set; }
        public Nullable<decimal> DIASEMNUM { get; set; }
    }
}
